air_pollution:
    root: 'C:\Users\sorapark\Github\UoL-DADT\data\air_pollution'
    data:
        air_quality: 'air_quality.csv'
        epi: 'epi_results.csv'
        output: 'manufacturing_output.csv'